[package]
name = "codewars_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "codewars_rust"
path = "src/lib.rs"
crate-type = ["lib"]
test = true
doctest = true

[dependencies]
