pub mod boolean_to_string;
pub mod boolean_to_word;
pub mod championship_points;
pub mod clock_past;
pub mod cockroach_speed;
pub mod dna_to_rna;
pub mod double_integer;
pub mod greet;
pub mod third_angle_of_triangle;
